name: 'saas_analytics'
version: '1.0.0'
config-version: 2

profile: 'saas_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  saas_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      core:
        +materialized: table
        +schema: marts
      saas_metrics:
        +materialized: table
        +schema: marts

vars:
  # Project variables
  start_date: '2022-01-01'
  end_date: '2024-12-31'

  # Unit economics assumptions (used in unit_economics model)
  # Business Context:
  # Synthetic data does not include marketing spend, so we parameterize CAC by segment.
  assumed_cac_smb: 600
  assumed_cac_mid_market: 2500
  assumed_cac_enterprise: 12000
